version: '3.4'

services:
  gestorventas_backend:
    image: gestorventasbackend:dev
    container_name: GestorVentas_Backend
    build:
      target: base
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "GestorVentas_Backend"
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=true
      - NUGET_FALLBACK_PACKAGES=
    volumes:
      - /Users/juanrodriguez/Projects/GestorVentasJc_Backend/GestorVentas_Backend:/app
      - /Users/juanrodriguez/Projects/GestorVentasJc_Backend:/src
      - /Users/juanrodriguez/vsdbg/vs2017u5:/remote_debugger:rw
      - /Users/juanrodriguez/.nuget/packages/:/root/.nuget/packages:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages  \"/app/bin/Debug/net6.0/GestorVentas_Backend.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
    tty: true